packages = [ "pandas", "Jinja2","html2text","numpy","beautifulsoup4", "lxml","matplotlib"]
[files]
"read.txt" = "read.txt"
"main8.py" = "main8.py"
"main.py" = "main.py"
"main1.py" = "main1.py"
"main2.py" = "main2.py"
"main3.py" = "main3.py"
"main4.py" = "main4.py"
"main5.py" = "main5.py"
"main6.py" = "main6.py"
"main7.py" = "main7.py"
"main9.py" = "main9.py"
"main10.py" = "main10.py"
"main11.py" = "main11.py"
"main12.py" = "main12.py"
"main13.py" = "main13.py"
"main14.py" = "main14.py"
"main15.py" = "main15.py"
"main16.py" = "main16.py"
"main17.py" = "main17.py"
"main18.py" = "main18.py"
"main19.py" = "main19.py"
"main20.py" = "main20.py"
"main21.py" = "main21.py"




